# Generated by Django 6.0.3 on 2026-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_adults_booking_arrival_time_booking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_country',
            field=models.CharField(blank=True, default='Nepal', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('prepay', 'Pre-payment (Bank Transfer)'), ('pay-at-checkin', 'Pay at Check-in'), ('bank-card', 'Bank Card on Arrival')], default='pay-at-checkin', max_length=20),
        ),
    ]
