# Generated by Django 6.0.3 on 2026-04-16 03:28

from django.db import migrations, models


def sync_customer_loyalty_cards(apps, schema_editor):
    User = apps.get_model("users", "User")
    Booking = apps.get_model("bookings", "Booking")
    per_card = 5
    for uid in User.objects.filter(role="customer").values_list("id", flat=True):
        n = Booking.objects.filter(
            user_id=uid, status__in=["confirmed", "checkout"]
        ).count()
        redeemed = (
            Booking.objects.filter(user_id=uid, loyalty_breakfast_card=True)
            .exclude(status="cancelled")
            .count()
        )
        balance = max(0, n // per_card - redeemed)
        User.objects.filter(pk=uid).update(loyalty_cards=balance)


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_booking_loyalty_fields"),
        ("users", "0005_remove_user_loyalty_points_user_loyalty_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='loyalty_breakfast_card',
            field=models.BooleanField(default=False, help_text='Guest requested to use one breakfast loyalty card on this booking (honoured at the hotel).'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='loyalty_points_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Legacy field; kept zero. Use loyalty_breakfast_card for breakfast redemption.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('prepay', 'Pre-payment (Bank Transfer)'), ('pay-at-checkin', 'Pay at Check-in'), ('bank-card', 'Bank Card on Arrival'), ('khalti', 'Khalti (online — sandbox / test)')], default='pay-at-checkin', max_length=20),
        ),
        migrations.RunPython(sync_customer_loyalty_cards, migrations.RunPython.noop),
    ]
