# Generated by Django 6.0.3 on 2026-04-01 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_hotelsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Room number must be numeric only (e.g. 101, 205).', regex='^\\d{1,10}$')]),
        ),
    ]
