# Generated by Django 6.0.3 on 2026-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_number_numeric_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='check_in_policy',
            field=models.CharField(blank=True, default='', help_text='e.g. From 2:00 PM — shown to guests where you surface policies.', max_length=120),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='check_out_policy',
            field=models.CharField(blank=True, default='', help_text='e.g. By 11:00 AM', max_length=120),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Main front desk or reservations phone (display only).', max_length=40),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short line under the hotel name on marketing or confirmation copy.', max_length=240),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='website_url',
            field=models.CharField(blank=True, default='', help_text='Public website link (include https:// when possible).', max_length=500, verbose_name='Website URL'),
        ),
    ]
