# Generated by Django 6.0.3 on 2026-04-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_loyalty_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="loyalty_points",
            new_name="loyalty_cards",
        ),
        migrations.AlterField(
            model_name="user",
            name="loyalty_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Breakfast loyalty cards available (earned 1 per 5 completed stays, minus redemptions).",
            ),
        ),
    ]
